### ISSUE TITLE
预售商品，请问一下这个是什么原因呀

### ISSUE THREAD

**Issue by wangcl567** [chou0212/monkey-master#12]
{
    "overSea": false,
    "orderXml": null,
    "cartXml": null,
    "noStockSkuIds": "",
    "reqInfo": null,
    "hasJxj": false,
    "addedServiceList": null,
    "sign": null,
    "pin": "jd_61fbd55ce85cf",
    "success": false,
    "overseaMerge": false,
    "resultCode": 0,
    "addressVO": {
          ...
    },
    "orderId": 0,
    "submitSkuNum": 0,
    "deductMoneyFlag": 0,
    "international": false,
    "orderType": 0,
    "goJumpOrderCenter": false,
    "payInfo": null,
    "cartEmpty": false,
    "scaleSkuInfoListVO": null,
    "purchaseSkuInfoListVO": null,
    "noSupportHomeServiceSkuList": null,
    "msgMobile": null,
    "msgUuid": null,
    "needCheckCode": false,
    "message": "获取用户订单信息失败"
}

**Comment by chou0212** [comment]
预售商品下单逻辑JD有变化，等更新

**Comment by wangcl567** [comment]
我去试了预售下单，控制台都看不出来哪一个是下单请求。
