### ISSUE TITLE
猴老师发生了甚么事？咋这样了怎么解决（来自不懂JS猴子的疑惑）

### ISSUE THREAD

**Issue by ChenJBBB** [chou0212/monkey-master#3]
![image](https://user-images.githubusercontent.com/52923919/102703763-fd37cc80-42ad-11eb-9038-75085f14ec35.png)

**Comment by chou0212** [comment]
看起来是没有安装 chrome 浏览器， 如果是windows的话，还需要自行修改chrome --headless的启动目录
https://github.com/chou0212/monkey-master/blob/50d6af416219a2a916de2560bbb92d585cebf8c2/util/browser.js#L7

**Comment by wangklhs** [comment]
请问要改成什么...

**Comment by chou0212** [comment]
> 请问要改成什么...

目前不需要改了
