### ISSUE TITLE
使用京东金融API出现下单失败请重试

### ISSUE THREAD

**Issue by greenhand88** [chou0212/monkey-master#30]

**Comment by greenhand88** [comment]
使用京东金融API出现下单失败请重试

**Comment by bigbigbigfish** [comment]
早都秒不了了，这个接口，估计里面的参数失效了，各种参数也不知道是啥啊。希望大家研究研究，这个流程非常少，这个是这个的特色啊。所有脚本都没有这简单接口。

**Comment by chou0212** [comment]
![QQ图片20210302223744](https://user-images.githubusercontent.com/2795904/109664348-01367380-7ba8-11eb-9c46-8f4783887cd6.png)
实测并未失效哈， 不过有些抢购是不支持这种方式的，不能判断的情况下建议两种方式同时使用

**Comment by bigbigbigfish** [comment]
那些抢购不支持？能从界面看出吗？

**Comment by chou0212** [comment]
> 那些抢购不支持？能从界面看出吗？

其实我不知道，期待分享- -

**Comment by bigbigbigfish** [comment]
{
  submitOrder: {
    Message: "啊哦，没有抢到商品，同账户或同IP只能抢购一件哟！别灰心，请返回购物车删除抢购商品后再提交订单吧！",
    SubmitSkuNum: 0,
    OrderId: 0,
    submitWithWmCard: "0",
    Flag: false,
    MessageType: 61029
  },
  code: 0,
  floors: []
}

这都没有成功，你判断code =0
