### ISSUE TITLE
购买 预约抢购 商品时，提示获取用户信息失败，是暂时不支持购买预约抢购商品么？

### ISSUE THREAD

**Issue by MaFuyan** [chou0212/monkey-master#31]

**Comment by chou0212** [comment]
JD预约抢购分为真抢购（某饮料）和 普通抢购，分别对应 提前秒杀/按时下单模式， 你需要详细描述遇到的问题

**Comment by MaFuyan** [comment]
是的，目前JD秒杀分为两种方式，一：在抢购时间开始前预约，商品自动加入购物车，商品在购物车中无法选中，到抢购时间，可以下单；二：不需要做任何操作，到抢购时间下单即可。
第二种抢购方式可以正常执行，第一种方式会下单失败，提示 “获取用户订单信息失败”。

**Comment by chou0212** [comment]
> 是的，目前JD秒杀分为两种方式，一：在抢购时间开始前预约，商品自动加入购物车，商品在购物车中无法选中，到抢购时间，可以下单；二：不需要做任何操作，到抢购时间下单即可。
> 第二种抢购方式可以正常执行，第一种方式会下单失败，提示 “获取用户订单信息失败”。

Duplicate of #23

**Comment by MaFuyan** [comment]
收到，感谢， 待会试一下 :)
