### ISSUE TITLE
二维码异常，扫描不起

### ISSUE THREAD

**Issue by yuzhouzhouba** [chou0212/monkey-master#46]
你们是咋处理的，为什么我的二维码长这样

![image](https://user-images.githubusercontent.com/10243546/118345647-8eaf2000-b568-11eb-8fd2-37059811e83b.png)

**Comment by jchenren** [comment]
一样的

**Comment by chou0212** [comment]
配置参数：openQrInNewWindow

**Comment by akahanaton** [comment]
Hi，openQrInNewWindow 改成true也识别不了

**Comment by doveeeee** [comment]
> Hi，openQrInNewWindow 改成true也识别不了

可以详细说明一下吗？该参数改为`true`时应该会弹出一个图片窗口以便扫码，是这个二维码识别不了还是没有弹出这个窗口呢？

**Comment by akahanaton** [comment]
谢谢回复，弹出了窗口，但是二维码无法识别，京东app扫描无反应

**Comment by akahanaton** [comment]
请问这一步是输入京东账号密码吗，能不能改成手动输入啊

**Comment by doveeeee** [comment]
> 谢谢回复，弹出了窗口，但是二维码无法识别，京东app扫描无反应

我这边测试是可以识别的呀，是否有可能是你的京东app版本过旧导致的？

**Comment by akahanaton** [comment]
我是最新版的京东app

**Comment by akahanaton** [comment]
用windows系统可以登录了，mac不行

**Comment by doveeeee** [comment]
> 用windows系统可以登录了，mac不行

mac系统应该是不可以的，有时间我在README里做个说明
