### ISSUE TITLE
部署在服务器上

### ISSUE THREAD

**Issue by caijillx** [chou0212/monkey-master#5]
我想将其部署在服务器上，之前部署在本地MacOS上可以弹出二维码，而在linux服务器由于无法弹出二维码则会直接报错，请问是否有办法解决？

**Comment by ChenJBBB** [comment]
我也是 毕竟要一直运行，我部署在EXSI虚拟机的Ubuntu server下，也不行

**Comment by chou0212** [comment]
应该都是因为没有装 chrome 或者路径不对，或者自己配上 eid fp 这些就不用依赖无头浏览器去获取。
实现 linux 上的全自动暂时不是目标。
