### ISSUE TITLE
预约抢购商品，似乎获取不到正确状态

### ISSUE THREAD

**Issue by shadowghost1213** [chou0212/monkey-master#7]
页面显示有货的状态，也能到订单提交页，但工具中始终显示暂无库存。
是否不支持预约抢购商品

**Comment by chou0212** [comment]
> 页面显示有货的状态，也能到订单提交页，但工具中始终显示暂无库存。
> 是否不支持预约抢购商品

支持的，提供一下 skuid 看下

**Comment by shadowghost1213** [comment]
> > 页面显示有货的状态，也能到订单提交页，但工具中始终显示暂无库存。
> > 是否不支持预约抢购商品
> 
> 支持的，提供一下 skuid 看下

100012043978，没错 [/狗头]

**Comment by chou0212** [comment]
> > > 页面显示有货的状态，也能到订单提交页，但工具中始终显示暂无库存。
> > > 是否不支持预约抢购商品
> > 
> > 
> > 支持的，提供一下 skuid 看下
> 
> 100012043978，没错 [/狗头]

。。。果然是没错，没错是秒杀商品，暂不支持秒杀， 实际上进入秒杀页面也是服务器随机分配名额，并不是手快就能买到的

**Comment by yijun-li-20** [comment]
请问现在100012043978还是那个接口吗，还是必须移动端
